### ISSUE TITLE
Crash when clicking the changelog button

### ISSUE THREAD

**Issue by apcro** [apcro/leafpicrevived#14]
Build version: v0.8.3 
Build date: 1979-11-30 00:00:00 
Current date: 2020-01-07 08:52:41 
Device: HUAWEI STK-LX1 
 
Stack trace:  
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.alienpants.leafpicrevived.debug-ooqxtXqxtFPKH343eLH5EQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.alienpants.leafpicrevived.debug-ooqxtXqxtFPKH343eLH5EQ==/lib/arm64, /data/app/com.alienpants.leafpicrevived.debug-ooqxtXqxtFPKH343eLH5EQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]] couldn't find "libbypass.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
	at java.lang.System.loadLibrary(System.java:1672)
	at in.uncod.android.bypass.Bypass.<clinit>(Bypass.java:35)
	at com.alienpants.leafpicrevived.util.AlertDialogsHelper.showChangelogDialog(AlertDialogsHelper.java:342)
	at com.alienpants.leafpicrevived.about.AboutActivity.onChangelog(AboutActivity.java:144)
	at com.alienpants.leafpicrevived.about.AboutActivity_ViewBinding$1.doClick(AboutActivity_ViewBinding.java:55)
	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
	at android.view.View.performClick(View.java:6659)
	at android.view.View.performClickInternal(View.java:6631)
	at android.view.View.access$3100(View.java:790)
	at android.view.View$PerformClick.run(View.java:26187)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by apcro** [comment]
This is caused by https://github.com/Uncodin/bypass

It might be best to replace this library with something else, or remove it entirely. It is only used to render the changelog markdown file in an Alert Dialog.
