### ISSUE TITLE
Crash when trying to view a video.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [apcro/leafpicrevived#2]
```
Build version: v0.8.1 
Build date: 1980-01-01 00:00:00 
Current date: 2019-10-02 22:12:20 
Device: Samsung SM-G930F 
 
Stack trace:  
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Point;
	at com.drew.metadata.mp4.boxes.TrackHeaderBox.a()
	at com.drew.metadata.mp4.Mp4BoxHandler.d()
	at com.drew.metadata.mp4.Mp4BoxHandler.a()
	at com.drew.imaging.mp4.Mp4Reader.a()
	at com.drew.imaging.mp4.Mp4Reader.a()
	at com.drew.imaging.mp4.Mp4Reader.a()
	at com.drew.imaging.mp4.Mp4Reader.a()
	at com.drew.imaging.mp4.Mp4MetadataReader.a()
	at com.drew.imaging.ImageMetadataReader.a()
	at com.drew.imaging.ImageMetadataReader.a()
	at com.drew.imaging.ImageMetadataReader.a()
	at com.alienpants.leafpicrevived.data.metadata.MetaDataItem.b()
	at com.alienpants.leafpicrevived.data.metadata.MetaDataItem.<init>()
	at com.alienpants.leafpicrevived.data.metadata.MetaDataItem.a()
	at com.alienpants.leafpicrevived.data.metadata.MetadataHelper.a()
	at com.alienpants.leafpicrevived.util.AlertDialogsHelper.a()
	at com.alienpants.leafpicrevived.activities.SingleMediaActivity.onOptionsItemSelected()
	at android.app.Activity.onMenuItemSelected(Activity.java:3208)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected()
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected()
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected()
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected()
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick()
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick()
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.a()
	at androidx.appcompat.view.menu.MenuBuilder.a()
	at androidx.appcompat.view.menu.MenuItemImpl.g()
	at androidx.appcompat.view.menu.MenuBuilder.a()
	at androidx.appcompat.view.menu.MenuPopup.onItemClick()
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
	at android.widget.AbsListView$3.run(AbsListView.java:4054)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.Point" on path: DexPathList[[zip file "/data/app/com.alienpants.leafpicrevived-1/base.apk"],nativeLibraryDirectories=[/data/app/com.alienpants.leafpicrevived-1/lib/arm64, /data/app/com.alienpants.leafpicrevived-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 40 more
```
 It also display the video thumbnail as a picture when looking it by sliding the medias. Despite being a panorama video (and thumbnail) it crop and zoom at the height of my phone the thumbnail when viewing it in portrait mode.

The crash in itself appended when you try to click on the video to view it from the gallery view (It doesn't work when trying to click on it during the slides).

**Comment by apcro** [comment]
This appears to be related to the metadata library https://github.com/drewnoakes/metadata-extractor, however the specific error that is appearing (`Didn't find class "java.awt.Point"`) has been fixed in v2.12.0 of the library, which is the version used in the current build.

I assume this is the build from the F-Droid release, so I will check the metadata for that release's build.

**Comment by PoorPocketsMcNewHold** [comment]
Forgot to precise that detail, but yes. It was the F-droid build.

-------- Message d'origine --------

**Comment by apcro** [comment]
Could you remove and reinstall from F-Droid? I've checked all the build tooling and the `build.gradle` does specify the correct version of the library. I also tested on my own device by removing all versions and installing directly from F-Droid, and the steps outlined above worked fine with a number of MP4 files.

If it happens again then I will investigate whether the F-Droid internal build process changes which version of third party libraries is used.
