### ISSUE TITLE
App Crash -> Crash Log

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [apcro/leafpicrevived#26]
App Crash -> Crash Log

Build version: v0.8.5 
Current date: 2020-02-29 04:00:45 
Device: Samsung SM-G960F 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.alienpants.leafpicrevived/com.alienpants.leafpicrevived.about.AboutActivity}: android.view.InflateException: Binary XML file line #128 in com.alienpants.leafpicrevived:layout/activity_about: Binary XML file line #128 in com.alienpants.leafpicrevived:layout/activity_about: Error inflating class com.alienpants.leafpicrevived.about.AboutLink
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: android.view.InflateException: Binary XML file line #128 in com.alienpants.leafpicrevived:layout/activity_about: Binary XML file line #128 in com.alienpants.leafpicrevived:layout/activity_about: Error inflating class com.alienpants.leafpicrevived.about.AboutLink
Caused by: android.view.InflateException: Binary XML file line #128 in com.alienpants.leafpicrevived:layout/activity_about: Error inflating class com.alienpants.leafpicrevived.about.AboutLink
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(Unknown Source:8)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.c(Unknown Source:23)
	at androidx.appcompat.app.AppCompatActivity.setContentView(Unknown Source:4)
	at com.alienpants.leafpicrevived.about.AboutActivity.onCreate(Unknown Source:6)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: android.view.InflateException: Binary XML file line #12 in com.alienpants.leafpicrevived:layout/view_about_link: Binary XML file line #12 in com.alienpants.leafpicrevived:layout/view_about_link: Error inflating class TextView
Caused by: android.view.InflateException: Binary XML file line #12 in com.alienpants.leafpicrevived:layout/view_about_link: Error inflating class TextView
Caused by: java.lang.RuntimeException: A 'Iconics.init(context)' has to happen first. Call from your application. Usually this happens via an 'IconicsDrawable' usage.
	at com.mikepenz.iconics.Iconics.a(Unknown Source:329)
	at com.mikepenz.iconics.Iconics.a(Unknown Source:5)
	at com.mikepenz.iconics.Iconics.a(Unknown Source:2)
	at com.mikepenz.iconics.Iconics.a(Unknown Source:5)
	at com.mikepenz.iconics.Iconics$BuilderView.a(Unknown Source:87)
	at com.mikepenz.iconics.utils.IconicsExtensionsKt.a(Unknown Source:22)
	at com.mikepenz.iconics.utils.IconicsExtensionsKt.a(Unknown Source:6)
	at com.mikepenz.iconics.context.IconicsFactory.b(Unknown Source:41)
	at com.mikepenz.iconics.context.IconicsFactory.a(Unknown Source:30)
	at com.mikepenz.iconics.context.InternalLayoutInflater$WrapperFactory2.onCreateView(Unknown Source:21)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
	at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(Unknown Source:8)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at com.alienpants.leafpicrevived.about.AboutLink.a(Unknown Source:11)
	at com.alienpants.leafpicrevived.about.AboutLink.<init>(Unknown Source:3)
	at com.alienpants.leafpicrevived.about.AboutLink.<init>(Unknown Source:1)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(Unknown Source:8)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.c(Unknown Source:23)
	at androidx.appcompat.app.AppCompatActivity.setContentView(Unknown Source:4)
	at com.alienpants.leafpicrevived.about.AboutActivity.onCreate(Unknown Source:6)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

**Comment by Tobias-B-Besemer** [comment]
Maybe this will help:
https://stackoverflow.com/questions/54472645/java-lang-noclassdeffounderror-failed-resolution-of-lcom-google-android-gms-co

**Comment by apcro** [comment]
This appears to be related to the Iconics library and increasing incompatiability with later versions of Android. There's an issue to replace this library (which is locked at a certain version at the moment): https://github.com/apcro/leafpicrevived/issues/21

This portion of the error log
```
Caused by: android.view.InflateException: Binary XML file line #12 in com.alienpants.leafpicrevived:layout/view_about_link: Error inflating class TextView
Caused by: java.lang.RuntimeException: A 'Iconics.init(context)' has to happen first. Call from your application. Usually this happens via an 'IconicsDrawable' usage.
```
shows an error trying to inflate an Android component (`TextView`), even though the named call (`Iconics.init(context)`) is called in the app lifecycle.

I've added an explicit call to this function within `AboutLink` prior to calling the inflator, although I've not been able to recreate this crash at all.
