### ISSUE TITLE
Advanced sharing crash

### ISSUE THREAD

**Issue by agent3bood** [apcro/leafpicrevived#6]
Hi and thanks for the awesome project

I have a crash when using this feature, device is pixel XL running Android 10.
steps open any image, click the menu, click on Advanced sharing, app will crash.
If you need more information or want me to test some fix on me device I am happy to help.
https://ibb.co/605jsZd

Build version: v0.8.2 
Build date: 1979-11-30 03:00:00 
Current date: 2019-12-25 23:30:25 
Device: Google Pixel XL 

 ```
Stack trace:  
android.view.InflateException: Binary XML file line #2 in com.alienpants.leafpicrevived:layout/dialog_advanced_sharing: Binary XML file line #2 in com.alienpants.leafpicrevived:layout/dialog_advanced_sharing: Error inflating class android.support.v7.widget.CardView
Caused by: android.view.InflateException: Binary XML file line #2 in com.alienpants.leafpicrevived:layout/dialog_advanced_sharing: Error inflating class android.support.v7.widget.CardView
Caused by: java.lang.ClassNotFoundException: android.support.v7.widget.CardView
 at java.lang.Class.classForName(Native Method)
 at java.lang.Class.forName(Class.java:454)
 at android.view.LayoutInflater.createView(LayoutInflater.java:815)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
 at com.mikepenz.iconics.context.InternalLayoutInflater.inflate(Unknown Source:8)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
 at com.alienpants.leafpicrevived.util.AlertDialogsHelper.a(Unknown Source:22)
 at com.alienpants.leafpicrevived.activities.SingleMediaActivity.onOptionsItemSelected(Unknown Source:716)
 at android.app.Activity.onMenuItemSelected(Activity.java:4137)
 at androidx.fragment.app.FragmentActivity.onMenuItemSelected(Unknown Source:0)
 at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(Unknown Source:0)
 at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(Unknown Source:2)
 at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(Unknown Source:2)
 at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(Unknown Source:5)
 at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Unknown Source:6)
 at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.a(Unknown Source:6)
 at androidx.appcompat.view.menu.MenuBuilder.a(Unknown Source:4)
 at androidx.appcompat.view.menu.MenuItemImpl.g(Unknown Source:14)
 at androidx.appcompat.view.menu.MenuBuilder.a(Unknown Source:12)
 at androidx.appcompat.view.menu.MenuPopup.onItemClick(Unknown Source:27)
 at android.widget.AdapterView.performItemClick(AdapterView.java:330)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
 at android.widget.AbsListView$3.run(AbsListView.java:4116)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.ClassNotFoundException: android.support.v7.widget.CardView
 ... 34 more
```

**Comment by apcro** [comment]
Thanks for logging this issue. I've found the bug and fixed it, and an updated version will be released on Google Play shortly.
