### ISSUE TITLE
Crash when viewing video details

### ISSUE THREAD

**Issue by apcro** [apcro/leafpicrevived#8]
1. Select a video
2. Choose details from the dot menu

Build version: v0.8.2 
Build date: 1979-11-30 00:00:00 
Current date: 2019-12-31 23:15:31 
Device: HUAWEI STK-LX1 
 
Stack trace:  
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Point;
	at com.drew.metadata.mp4.boxes.TrackHeaderBox.addMetadata(TrackHeaderBox.java:77)
	at com.drew.metadata.mp4.Mp4BoxHandler.processTrackHeader(Mp4BoxHandler.java:116)
	at com.drew.metadata.mp4.Mp4BoxHandler.processBox(Mp4BoxHandler.java:86)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:58)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
	at com.drew.imaging.mp4.Mp4Reader.extract(Mp4Reader.java:42)
	at com.drew.imaging.mp4.Mp4MetadataReader.readMetadata(Mp4MetadataReader.java:57)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:178)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:125)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:104)
	at com.alienpants.leafpicrevived.data.metadata.MetaDataItem.load(MetaDataItem.java:76)
	at com.alienpants.leafpicrevived.data.metadata.MetaDataItem.<init>(MetaDataItem.java:49)
	at com.alienpants.leafpicrevived.data.metadata.MetaDataItem.getMetadata(MetaDataItem.java:45)
	at com.alienpants.leafpicrevived.data.metadata.MetadataHelper.getMainDetails(MetadataHelper.java:34)
	at com.alienpants.leafpicrevived.util.AlertDialogsHelper.getDetailsDialog(AlertDialogsHelper.java:228)
	at com.alienpants.leafpicrevived.activities.SingleMediaActivity.onOptionsItemSelected(SingleMediaActivity.java:659)
	at android.app.Activity.onMenuItemSelected(Activity.java:3742)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:321)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1234)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3234)
	at android.widget.AbsListView$3.run(AbsListView.java:4210)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.Point" on path: DexPathList[[zip file "/data/app/com.alienpants.leafpicrevived.debug-xL53ju0Omz7OGSwSEdReSw==/base.apk"],nativeLibraryDirectories=[/data/app/com.alienpants.leafpicrevived.debug-xL53ju0Omz7OGSwSEdReSw==/lib/arm64, /data/app/com.alienpants.leafpicrevived.debug-xL53ju0Omz7OGSwSEdReSw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 40 more

**Comment by apcro** [comment]
This appears to be related to the current released version of the metadata extractor still relying on a deprecated library. This is fixed in https://github.com/drewnoakes/metadata-extractor/pull/409, which is not yet released.
